server:
  servlet:
    context-path: /cktest
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://42.192.219.87:3306/cktest?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/tyxtest?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
logging:
  level:
    root: info
    com.tyx.cktest.mapper: trace
